### ISSUE TITLE
I would like to talk to you like a civilized person please.

### ISSUE THREAD

**Issue by CutFlame** [GamingManPro/mcd-save-editor#1]
I have an idea that I want to know your thoughts on. Can you message me on Discord please?

**Comment by GamingManPro** [comment]
well whats your discord

**Comment by GamingManPro** [comment]
**[Removed]** if you want to message me

**Comment by CutFlame** [comment]
I'm **[Removed]**

**Comment by GamingManPro** [comment]
Accepted your request
